### ISSUE TITLE
Deploying the Stack

### ISSUE THREAD

**Issue by adarkkiss** [benpiper/architecting-reliability-aws#1]
Hello.
I am VERY new to coding and just started working on my AWS for architect. I was working through the M5 section in plural sight about adding your template to the command line and it keeps saying that I am denied access. I am not sure what I am doing wrong and was wondering if you had any guidance please.

![M5 error](https://user-images.githubusercontent.com/98498048/151680861-c00c2ed1-d808-4909-a2ab-4e6337890481.png)

C:\architecting-reliability-aws-master\architecting-reliability-aws-master\m5>aws s3 cp network-stack.json s3://benpiper.com-cftemplates
upload failed: .\network-stack.json to s3://benpiper.com-cftemplates/network-stack.json An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

I tried to look up what it meant but kept finding that the S3 permissions need to be changed? I am not entirely sure.
I was able to do the first two steps with no issues validating the cloudformation templates.

I also decided to go with your template and did not add my own S3

Thank you for the help!
Kim

**Comment by benpiper** [comment]
The issue is that you're attempting to upload the template to my S3 bucket (`benpiper.com-cftemplates`). Since you plan to use the template as-is, there's no need to upload it.
